[package]
name = "zeta"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1"
inkwell = { version = "0.19", features = ["llvm18-1"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
