[package]
name = "zeta"
version = "0.0.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
inkwell = { version = "0.7.0", features = ["llvm20-1"] }
rayon = "1.8"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12.24", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "zeta_bench"
harness = false
