[package]
name = "zeta"
version = "0.0.0"
edition = "2024"

[dependencies]
nom = "7.1"
inkwell = { version = "0.7.0", features = ["llvm18-0"] }
rayon = "1.8"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "zeta_bench"
harness = false
